"""Synthesis agent: deterministic gap detection plus LLM report generation.

Citations and the methodology-comparison table are assembled deterministically
from retrieved metadata rather than generated by the LLM, so the report cannot
contain hallucinated references.
"""

from __future__ import annotations

from collections import Counter

from pydantic import BaseModel, Field

from app.agents.grounding import grounding_checker
from app.agents.verification import VerificationResult, verify_report
from app.core import events
from app.core.llm import LLMResponse, llm_client
from app.graph.state import (
    PaperAnalysis,
    PaperMetadata,
    ResearchGap,
    ResearchPlan,
    ResearchReport,
)

UNDER_COVERAGE_THRESHOLD = 0.2
ISOLATED_METRIC_MAX_PAPERS = 2

GAP_SYSTEM = (
    "You are a critical research analyst. Given paper analyses and dataset/metric "
    "coverage observations, identify 3-5 specific, concrete research gaps. Each gap "
    "must reference specific papers by title. A gap is never vague ('more research "
    "needed') but specific ('No paper evaluates X on multilingual benchmarks despite "
    "3 papers claiming language-agnostic performance'). Return JSON only."
)

REPORT_SYSTEM = (
    "You are a senior research scientist writing a literature review. Using the paper "
    "analyses, the detected research gaps, and the plan, produce a rigorous synthesis. "
    "Write a 2-3 paragraph executive summary, identify concrete observed trends, and "
    "propose concrete future directions. Reference findings by paper title. "
    "Return JSON only."
)


class _GapResponse(BaseModel):
    """Internal wrapper so gap detection can return a list via structured output."""

    gaps: list[ResearchGap] = Field(default_factory=list)


class _ReportNarrative(BaseModel):
    """LLM-authored narrative portions of the report."""

    executive_summary: str = ""
    trends: list[str] = Field(default_factory=list)
    future_directions: list[str] = Field(default_factory=list)


def detect_gap_signals(analyses: list[PaperAnalysis]) -> dict:
    """Compute deterministic dataset/metric coverage signals.

    Datasets appearing in fewer than 20% of papers are flagged as under-covered;
    metrics used by fewer than two papers are flagged as isolated. These signals
    seed the LLM gap-analysis prompt with concrete, non-hallucinated evidence.
    """
    total = len(analyses)
    dataset_counts: Counter[str] = Counter()
    metric_counts: Counter[str] = Counter()
    for analysis in analyses:
        for dataset in {d.strip() for d in analysis.datasets if d.strip()}:
            dataset_counts[dataset] += 1
        for metric in {m.strip() for m in analysis.metrics if m.strip()}:
            metric_counts[metric] += 1

    under_covered = (
        [
            dataset
            for dataset, count in dataset_counts.items()
            if count / total < UNDER_COVERAGE_THRESHOLD
        ]
        if total
        else []
    )
    isolated_metrics = [
        metric for metric, count in metric_counts.items() if count < ISOLATED_METRIC_MAX_PAPERS
    ]
    return {
        "total_papers": total,
        "dataset_counts": dict(dataset_counts),
        "under_covered_datasets": sorted(under_covered),
        "isolated_metrics": sorted(isolated_metrics),
    }


def _format_authors(authors: list[str]) -> str:
    """Render an author list as 'A, B, C' or 'A et al.' beyond three names."""
    if not authors:
        return "Unknown"
    if len(authors) <= 3:
        return ", ".join(authors)
    return f"{authors[0]} et al."


def _clean_cell(text: str) -> str:
    """Make a string safe for a markdown table cell."""
    return " ".join((text or "").split()).replace("|", "\\|")


def build_citations(papers: list[PaperMetadata]) -> list[dict]:
    """Build a numbered citation list directly from paper metadata."""
    citations: list[dict] = []
    for index, paper in enumerate(papers, start=1):
        citations.append(
            {
                "index": index,
                "arxiv_id": paper.arxiv_id,
                "authors": _format_authors(paper.authors),
                "title": paper.title,
                "venue": paper.venue or "",
                "year": paper.year or "",
                "url": paper.url or "",
            }
        )
    return citations


def build_methodology_rows(
    analyses: list[PaperAnalysis], papers: list[PaperMetadata]
) -> list[dict]:
    """Build methodology-comparison rows by joining analyses to paper titles."""
    title_by_id = {p.paper_id: p.title for p in papers if p.paper_id}
    rows: list[dict] = []
    for analysis in analyses:
        rows.append(
            {
                "paper": title_by_id.get(analysis.paper_id, analysis.paper_id or "Unknown"),
                "method": analysis.methodology,
                "datasets": ", ".join(analysis.datasets),
                "key_metric": analysis.metrics[0] if analysis.metrics else "",
                "result": analysis.key_results,
            }
        )
    return rows


def assemble_markdown(
    plan: ResearchPlan,
    narrative: _ReportNarrative,
    methodology_rows: list[dict],
    gaps: list[ResearchGap],
    citations: list[dict],
    verification: VerificationResult | None = None,
) -> str:
    """Render the final report markdown in the mandated section layout.

    When a ``verification`` result is supplied, each reference is prefixed with a
    confidence badge (✅ grounded / ⚠️ unverified) and a "Verification Notes"
    section listing any unsupported references is appended.
    """
    verified_by_index = (
        {check.index: check.verified for check in verification.citations}
        if verification
        else {}
    )
    lines: list[str] = [f"# Research Analysis: {plan.goal}", ""]

    lines += ["## Executive Summary", "", narrative.executive_summary or "_No summary._", ""]

    lines += [
        "## Methodology Comparison",
        "",
        "| Paper | Method | Datasets | Key Metric | Result |",
        "|-------|--------|----------|------------|--------|",
    ]
    for row in methodology_rows:
        lines.append(
            "| {paper} | {method} | {datasets} | {key_metric} | {result} |".format(
                paper=_clean_cell(row["paper"]),
                method=_clean_cell(row["method"]),
                datasets=_clean_cell(row["datasets"]),
                key_metric=_clean_cell(row["key_metric"]),
                result=_clean_cell(row["result"]),
            )
        )
    lines.append("")

    lines += ["## Research Trends", ""]
    lines += [f"- {trend}" for trend in narrative.trends] or ["- No clear trends identified."]
    lines.append("")

    lines += ["## Research Gaps", ""]
    if gaps:
        for idx, gap in enumerate(gaps, start=1):
            evidence = "; ".join(gap.supporting_evidence)
            lines.append(f"{idx}. **{gap.description}**")
            if gap.opportunity:
                lines.append(f"   - Opportunity: {gap.opportunity}")
            if evidence:
                lines.append(f"   - Evidence: {evidence}")
    else:
        lines.append("No significant gaps detected.")
    lines.append("")

    lines += ["## Future Directions", ""]
    if narrative.future_directions:
        lines += [f"{idx}. {item}" for idx, item in enumerate(narrative.future_directions, 1)]
    else:
        lines.append("No future directions proposed.")
    lines.append("")

    lines += ["## References", ""]
    for cite in citations:
        badge = ""
        if verification is not None:
            badge = "✅ " if verified_by_index.get(cite["index"], False) else "⚠️ "
        lines.append(
            f"{badge}[{cite['index']}] {cite['authors']}. {cite['title']}. "
            f"{cite['venue']}, {cite['year']}. {cite['url']}".strip()
        )
    lines.append("")

    grounding = verification.grounding if verification is not None else None
    ungrounded = (
        [c for c in grounding["claims"] if not c["grounded"]] if grounding else []
    )
    if verification is not None and (verification.unsupported_references or ungrounded):
        lines += ["## Verification Notes", ""]
        lines += [f"- ⚠️ {note}" for note in verification.unsupported_references]
        if grounding:
            grounded = grounding["grounded_claims"]
            total = grounding["total_claims"]
            lines.append(
                f"- Entailment grounding: {grounded}/{total} cited claims supported "
                f"by their sources."
            )
            for claim in ungrounded:
                refs = ", ".join(f"[{i}]" for i in claim["citation_indices"])
                lines.append(
                    f"  - ⚠️ Weakly grounded ({claim['entailment']:.2f}) {refs}: "
                    f"{claim['claim']}"
                )
        lines.append("")

    return "\n".join(lines)


def _compact_analyses(
    analyses: list[PaperAnalysis], papers: list[PaperMetadata]
) -> list[dict]:
    """Produce a token-light view of analyses for LLM prompts."""
    title_by_id = {p.paper_id: p.title for p in papers if p.paper_id}
    return [
        {
            "title": title_by_id.get(a.paper_id, "Unknown"),
            "methodology": a.methodology,
            "datasets": a.datasets,
            "metrics": a.metrics,
            "key_results": a.key_results,
            "limitations": a.limitations,
        }
        for a in analyses
    ]


async def _detect_gaps(
    plan: ResearchPlan,
    compact: list[dict],
    signals: dict,
) -> tuple[list[ResearchGap], LLMResponse]:
    """Run the LLM gap-analysis pass over the deterministic signals."""
    import json

    messages = [
        {"role": "system", "content": GAP_SYSTEM},
        {
            "role": "user",
            "content": (
                f"Research goal: {plan.goal}\n\n"
                f"Coverage observations:\n{json.dumps(signals, indent=2)}\n\n"
                f"Paper analyses:\n{json.dumps(compact, indent=2)}"
            ),
        },
    ]
    response, usage = await llm_client.structured_complete(
        messages, _GapResponse, use_reasoning=True
    )
    return response.gaps, usage


async def _generate_narrative(
    plan: ResearchPlan,
    compact: list[dict],
    gaps: list[ResearchGap],
) -> tuple[_ReportNarrative, LLMResponse]:
    """Run the LLM narrative pass (summary, trends, future directions)."""
    import json

    gap_text = json.dumps([g.model_dump() for g in gaps], indent=2)
    messages = [
        {"role": "system", "content": REPORT_SYSTEM},
        {
            "role": "user",
            "content": (
                f"Research goal: {plan.goal}\n"
                f"Subtopics: {', '.join(plan.subtopics)}\n\n"
                f"Detected research gaps:\n{gap_text}\n\n"
                f"Paper analyses:\n{json.dumps(compact, indent=2)}"
            ),
        },
    ]
    return await llm_client.structured_complete(
        messages, _ReportNarrative, use_reasoning=True
    )


def _annotate_citations(citations: list[dict], verification: VerificationResult) -> None:
    """Stamp each citation dict with its verification verdict in place."""
    verdicts = {check.index: check for check in verification.citations}
    for cite in citations:
        check = verdicts.get(cite["index"])
        if check is not None:
            cite["verified"] = check.verified
            cite["match_score"] = check.score


def narrative_text_of(
    executive_summary: str, trends: list[str], future_directions: list[str]
) -> str:
    """Join the cited narrative fields into the text grounding/verification scans.

    Single source of truth for "what counts as the narrative" so the synthesis-time
    check and the ``/api/evals`` re-scan stay in lockstep.
    """
    return " ".join([executive_summary or "", *(trends or []), *(future_directions or [])])


async def run_synthesis(
    analyses: list[PaperAnalysis],
    papers: list[PaperMetadata],
    plan: ResearchPlan,
    session_id: str = "",
) -> tuple[ResearchReport, LLMResponse, VerificationResult]:
    """Generate the final report from analyses, papers and the plan.

    Performs deterministic gap detection, an LLM gap pass, and an LLM narrative
    pass, then assembles the methodology table, citations and markdown from the
    retrieved metadata. Runs citation grounding/hallucination detection, emits a
    ``citation_verification`` event, and returns the report, aggregate LLM usage
    and the verification result.
    """
    citations = build_citations(papers)
    methodology_rows = build_methodology_rows(analyses, papers)

    if not analyses:
        verification = verify_report(citations, papers, "")
        _annotate_citations(citations, verification)
        summary = (
            f"{len(papers)} paper(s) were found but none could be analyzed for this query."
            if papers
            else "No papers were found for this query."
        )
        empty = ResearchReport(
            executive_summary=summary,
            methodology_comparison=methodology_rows,
            research_gaps=[],
            trends=[],
            future_directions=[],
            citations=citations,
            # Render through assemble_markdown so the References and any
            # Verification Notes still appear when papers were found.
            markdown_content=assemble_markdown(
                plan, _ReportNarrative(executive_summary=summary), methodology_rows,
                [], citations, verification,
            ),
        )
        await events.citation_verification(session_id, verification.model_dump())
        return empty, LLMResponse(content="", tokens=0, cost_usd=0.0, model=""), verification

    signals = detect_gap_signals(analyses)
    compact = _compact_analyses(analyses, papers)

    gaps, gap_usage = await _detect_gaps(plan, compact, signals)
    narrative, narrative_usage = await _generate_narrative(plan, compact, gaps)

    narrative_text = narrative_text_of(
        narrative.executive_summary, narrative.trends, narrative.future_directions
    )
    verification = verify_report(citations, papers, narrative_text)
    grounding = await grounding_checker.check(narrative_text, papers)
    if grounding is not None:
        verification.grounding = grounding.model_dump()
    _annotate_citations(citations, verification)

    markdown = assemble_markdown(
        plan, narrative, methodology_rows, gaps, citations, verification
    )
    report = ResearchReport(
        executive_summary=narrative.executive_summary,
        methodology_comparison=methodology_rows,
        research_gaps=gaps,
        trends=narrative.trends,
        future_directions=narrative.future_directions,
        citations=citations,
        markdown_content=markdown,
    )
    aggregate = LLMResponse(
        content="",
        tokens=gap_usage.tokens + narrative_usage.tokens,
        cost_usd=round(gap_usage.cost_usd + narrative_usage.cost_usd, 6),
        model=narrative_usage.model,
    )
    await events.citation_verification(session_id, verification.model_dump())
    return report, aggregate, verification
